apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-external-secret
  namespace: future-cloud-engineer
spec:
  refreshInterval: 1h # 每一小時自動去 AWS 同步一次密碼
  secretStoreRef:
    name: aws-secretsmgr
    kind: SecretStore
  target:
    name: postgres-secret # name of kind: Secret
    template:
      data:
        DATABASE_URL: "postgresql+psycopg://{{ .user }}:{{ .pass }}@postgres:5432/cloud_learning"
        POSTGRES_USER: "{{ .user }}"
        POSTGRES_PASSWORD: "{{ .pass }}"
  data:
  - secretKey: user
    remoteRef:
      key: future-cloud/postgres-pass
      property: username
  - secretKey: pass
    remoteRef:
      key: future-cloud/postgres-pass
      property: password