apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: future-cloud-engineer
spec:
  accessModes:
    - ReadWriteOnce # 代表這塊硬碟同時只能被一個 Node 掛載
  resources:
    requests:
      storage: 1Gi # 申請 1GB 空間